steps:
# Build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/proyecto-final-grupo-16/abcall-web', '.']
# Push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/proyecto-final-grupo-16/abcall-web']
# Deploy container image to Cloud Run
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: ['run', 'deploy', 'abcall-web', '--image', 'gcr.io/proyecto-final-grupo-16/abcall-web', '--region', 'us-central1']
images:
- gcr.io/proyecto-final-grupo-16/abcall-web
options:
  logging: CLOUD_LOGGING_ONLY