name: CI checks

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Use Node.js v20
      uses: actions/setup-node@v4.0.4
      with:
        node-version: 20.9.0
    - name: npm install and npm run build
      run: |
        npm ci --force
        npm run build
    - name: Lint
      run: |
        npm run lint
    - name: npm test
      run: |
        npm run test
